Models and all the possible errors. Will add more in future
AA1999/Disthon pull request #7
Opened 2021-10-05 22:54 UTC by AA1999

2021-10-05 23:05 UTC, sebkuip requested changes
There is also a random binary file, if it could be removed:
discord/types/_disthon_discord_types_snowflake.py1.stats

2021-10-06 06:15 UTC, AA1999 commented on discord/client/client.py
> +from discord.api import intents as intent, handler, websocket
This must be an older update of your code

2021-10-06 06:16 UTC, AA1999 commented on discord/errors/discordexception.py
> +import traceback
I'll work on getting them all in one file

2021-10-11 19:07 UTC, sebkuip commented on discord/abc/abstarctuser.py
> +class AbstractUser(DiscordObject):
This file still isn't deleted. This is the one with the typo in the name

2021-10-11 19:10 UTC, sebkuip commented on discord/abc/discordobject.py
> +from abc import ABCMeta
Where is this ABCMeta defined?

2021-10-11 19:11 UTC, sebkuip commented on discord/abc/discordobject.py
> +        return self.id.id >> 22
self.id.id looks extremely off and wrong.

2021-10-11 19:13 UTC, sebkuip commented on discord/activity/activity.py
> +class Activity(BaseActivity):
`__slots__` is missing here

2021-10-11 19:14 UTC, sebkuip commented on discord/activity/baseactivity.py
> +    def __init(self, **kwargs):
forgot the right side `__` for the init

2021-10-11 19:15 UTC, sebkuip commented on discord/activity/presenseassets.py
> +        pass
Either fill this in or add a notimplementederror

2021-10-11 19:16 UTC, sebkuip commented on discord/activity/presenseassets.py
> +class PresenceAssets(dict[Snowflake, str]):
`__slots__` is missing

2021-10-11 19:17 UTC, sebkuip commented on discord/activity/rawactivityassets.py
> +class RawActivityAssets(TypedDict):
`__slots__` is missing

2021-10-11 19:18 UTC, sebkuip commented on discord/api/handler.py
> +            if not 200 <= r.status < 300 and r.status == 401:
The nested if was to be able to add more error codes in the future for different types of errors

2021-10-11 19:20 UTC, sebkuip commented on discord/api/websocket.py
> +                    '$browser': 'discord',
We're not discord accessing itself. We're disthon the library

2021-10-11 19:24 UTC, sebkuip commented on discord/color/color.py
> +                for c in color[1]:
Slicing forgotten

2021-10-11 19:24 UTC, sebkuip commented on discord/color/color.py
> +                for c in color[2]:
Same as above. Did you forget slicing?

2021-10-11 19:25 UTC, sebkuip commented on discord/color/color.py
> +                if not color[2].isdigit():
Slicing was forgotten here

2021-10-11 19:25 UTC, sebkuip commented on discord/color/color.py
> +                if not color[1].isdigit():
Why the `[1]` index here? Did you forget a `:` for slicing?

2021-10-11 19:29 UTC, sebkuip commented on discord/errors/discordexception.py
> +import traceback
Whilst you did move them all to 1 file, you forgot to delete the separate files

2021-10-11 19:30 UTC, sebkuip commented on discord/guild/guild.py
> +class BanEntry(NamedTuple):
Maybe add `__slots__`?

2021-10-11 19:30 UTC, sebkuip commented on discord/guild/guild.py
> +class GuildLimit(NamedTuple):
`__slots__` here too?

2021-10-11 19:31 UTC, sebkuip commented on discord/guild/guild.py
> +        'owner.id'
Did you mean `owner_id`?

2021-10-11 19:31 UTC, sebkuip commented on discord/guild/guild.py
> +        'mfa.level'
Did you mean `moderation_level`? MFA is just a True/False for guilds

2021-10-11 19:33 UTC, sebkuip commented on discord/guild/guild.py
> +        self._members: dict[Snowflake, Member] = {}
I assume these are for the cache and not directly for the guild? Are they misplaced?

2021-10-11 19:34 UTC, sebkuip commented on discord/interaction/interaction.py
> +    pass
Possibly make this `notimplementederror`?

2021-10-11 19:35 UTC, sebkuip commented on discord/internal/cache.py
> +
Inside this folder there is a random .stats file. Not sure if that's supposed to be there?

2021-10-11 19:35 UTC, sebkuip commented on discord/internal/cache.py
> +    _handler: Handler
Why is handler not in slots?

2021-10-11 19:37 UTC, sebkuip commented on discord/internal/cache.py
> +    _cache: dict[Snowflake, User]
This is already set in the baseclass as a slot. This is redundant. Please also adress this in every other type of cache thanks

2021-10-11 19:38 UTC, sebkuip commented on discord/member/member.py
> +
Add `__slots__` and a guild

2021-10-11 19:40 UTC, sebkuip commented on discord/role/role.py
> +            raise NotImplementedError
I'd say if we're not comparing roles we should raise a typeerror

2021-10-11 19:42 UTC, sebkuip commented on discord/types/snowflake.py
> +
There is a random .stats file. Could you remove it?

2021-10-11 19:44 UTC, sebkuip commented on discord/types/banner.py
> +    def colour(self):
Why not make this a `colour = color` since it's just an alias?

2021-10-11 19:44 UTC, sebkuip commented on discord/types/rolepayload.py
> +    bot_id: Snowflake
Why not `__slots__`?

2021-10-11 19:45 UTC, sebkuip commented on discord/types/userpayload.py
> +    id: Snowflake
Please add `__slots__`

2021-10-11 19:45 UTC, sebkuip commented on discord/user/baseuser.py
> +
Random .stats file here too

2021-10-18 19:46 UTC, closed without merging